// Liens méthode → carte (théorème/propriété). Généré, éditable à la main.
// Résolu au démarrage par (chapitreId, carteTitre) → carte_id stable.
export const LINKS = [
  { methodeId: 1, chapitreId: 'ma-series', carteTitre: "Série de Riemann" },
  { methodeId: 2, chapitreId: 'ma-series', carteTitre: "Règle de d'Alembert" },
  { methodeId: 3, chapitreId: 'ma-series', carteTitre: "Comparaison par équivalent / grand O" },
  { methodeId: 4, chapitreId: 'ma-series', carteTitre: "Série de Riemann" },
  { methodeId: 5, chapitreId: 'ma-series', carteTitre: "Comparaison par équivalent / grand O" },
  { methodeId: 6, chapitreId: 'ma-series', carteTitre: "Convergence d'une SATP" },
  { methodeId: 7, chapitreId: 'ma-cvg', carteTitre: "Comparaison de fonctions positives" },
  { methodeId: 8, chapitreId: 'ma-series', carteTitre: "Comparaison par équivalent / grand O" },
  { methodeId: 9, chapitreId: 'ma-series', carteTitre: "Théorème de Cesàro" },
  { methodeId: 10, chapitreId: 'ma-int', carteTitre: "Étudier la nature d'une intégrale impropre" },
  { methodeId: 11, chapitreId: 'ma-cvg', carteTitre: "Continuité sous le signe intégrale" },
  { methodeId: 12, chapitreId: 'ma-sfn', carteTitre: "Critère pratique de non-convergence uniforme" },
  { methodeId: 13, chapitreId: 'ma-int', carteTitre: "Comparaison série-intégrale" },
  { methodeId: 14, chapitreId: 'ma-int', carteTitre: "Intégration par parties généralisée" },
  { methodeId: 15, chapitreId: 'ma-se', carteTitre: "Calculer le rayon de convergence" },
  { methodeId: 16, chapitreId: 'ma-se', carteTitre: "Série entière" },
  { methodeId: 17, chapitreId: 'ma-se', carteTitre: "Théorème d'Abel radial (hors programme commun, utile)" },
  { methodeId: 18, chapitreId: 'ma-se', carteTitre: "Unicité du développement" },
  { methodeId: 19, chapitreId: 'ma-se', carteTitre: "Série entière" },
  { methodeId: 20, chapitreId: 'ma-sfn', carteTitre: "Critère pratique de non-convergence uniforme" },
  { methodeId: 21, chapitreId: 'ma-cvg', carteTitre: "Continuité sous le signe intégrale" },
  { methodeId: 22, chapitreId: 'ma-sfn', carteTitre: "Approximation par fonctions en escalier / affines" },
  { methodeId: 23, chapitreId: 'ma-cvg', carteTitre: "Comparaison de fonctions positives" },
  { methodeId: 24, chapitreId: 'ma-cvg', carteTitre: "Appliquer le théorème de convergence dominée" },
  { methodeId: 25, chapitreId: 'ma-cvg', carteTitre: "Calculer une intégrale à paramètre" },
  { methodeId: 26, chapitreId: 'ma-int', carteTitre: "Comparaison et majoration" },
  { methodeId: 27, chapitreId: 'ma-int', carteTitre: "Comparaison série-intégrale" },
  { methodeId: 28, chapitreId: 'ma-ed', carteTitre: "EDL scalaire d'ordre 1" },
  { methodeId: 29, chapitreId: 'ma-ed', carteTitre: "Méthode de variation des constantes" },
  { methodeId: 30, chapitreId: 'ma-ed', carteTitre: "Cauchy linéaire — forme générale" },
  { methodeId: 31, chapitreId: 'ma-ed', carteTitre: "Cauchy linéaire — forme générale" },
  { methodeId: 32, chapitreId: 'ma-ed', carteTitre: "Cauchy linéaire — forme générale" },
  { methodeId: 33, chapitreId: 'ma-ed', carteTitre: "Cauchy linéaire — forme générale" },
  { methodeId: 34, chapitreId: 'ma-fvect', carteTitre: "Inégalité des accroissements finis (version vectorielle)" },
  { methodeId: 35, chapitreId: 'ma-se', carteTitre: "Unicité du développement" },
  { methodeId: 36, chapitreId: 'ma-se', carteTitre: "Convergence normale sur tout compact" },
  { methodeId: 37, chapitreId: 'ma-evn', carteTitre: "Image continue d'un compact, théorème des bornes" },
  { methodeId: 38, chapitreId: 'ma-evn', carteTitre: "Suite de Cauchy, espace complet" },
  { methodeId: 39, chapitreId: 'ma-evn', carteTitre: "Image continue d'un compact, théorème des bornes" },
  { methodeId: 40, chapitreId: 'ma-evn', carteTitre: "Équivalence des normes en dimension finie" },
  { methodeId: 41, chapitreId: 'ma-red', carteTitre: "Critère de diagonalisation" },
  { methodeId: 42, chapitreId: 'ma-red', carteTitre: "Critère de diagonalisation" },
  { methodeId: 43, chapitreId: 'ma-red', carteTitre: "Critère de diagonalisation" },
  { methodeId: 44, chapitreId: 'ma-red', carteTitre: "Polynôme caractéristique" },
  { methodeId: 45, chapitreId: 'ma-red', carteTitre: "Critère de diagonalisation" },
  { methodeId: 46, chapitreId: 'ma-red', carteTitre: "Critère de diagonalisation" },
  { methodeId: 47, chapitreId: 'ma-red', carteTitre: "Décomposition de Dunford" },
  { methodeId: 48, chapitreId: 'ma-red', carteTitre: "Critère de diagonalisation" },
  { methodeId: 49, chapitreId: 'ma-red', carteTitre: "Polynôme caractéristique" },
  { methodeId: 50, chapitreId: 'ma-red', carteTitre: "Décomposition de Dunford" },
  { methodeId: 51, chapitreId: 'ma-red', carteTitre: "Polynôme caractéristique" },
  { methodeId: 52, chapitreId: 'ma-eucl', carteTitre: "Existence de l'adjoint" },
  { methodeId: 53, chapitreId: 'ma-eucl', carteTitre: "Réduction des isométries (dim 3, directe)" },
  { methodeId: 54, chapitreId: 'ma-eucl', carteTitre: "Endomorphisme autoadjoint (symétrique)" },
  { methodeId: 55, chapitreId: 'ma-red', carteTitre: "Critère de diagonalisation" },
  { methodeId: 56, chapitreId: 'ma-alg', carteTitre: "Déterminant par blocs" },
  { methodeId: 57, chapitreId: 'ma-alg', carteTitre: "Déterminant de Vandermonde" },
  { methodeId: 58, chapitreId: 'ma-red', carteTitre: "Critère de diagonalisation" },
  { methodeId: 59, chapitreId: 'ma-alg', carteTitre: "Théorème du rang" },
  { methodeId: 60, chapitreId: 'ma-alg', carteTitre: "Théorème du rang" },
  { methodeId: 61, chapitreId: 'ma-alg', carteTitre: "Théorème du rang" },
  { methodeId: 62, chapitreId: 'ma-proba', carteTitre: "Probabilité conditionnelle" },
  { methodeId: 63, chapitreId: 'ma-proba', carteTitre: "Formule des probabilités totales" },
  { methodeId: 64, chapitreId: 'ma-proba', carteTitre: "Indépendance d'événements" },
  { methodeId: 65, chapitreId: 'ma-proba', carteTitre: "Probabilité conditionnelle" },
  { methodeId: 66, chapitreId: 'ma-va', carteTitre: "Formule de transfert" },
  { methodeId: 67, chapitreId: 'ma-proba', carteTitre: "Inégalité de Markov" },
  { methodeId: 68, chapitreId: 'ma-proba', carteTitre: "Variance d'une somme" },
  { methodeId: 69, chapitreId: 'ma-proba', carteTitre: "Indépendance d'événements" },
  { methodeId: 70, chapitreId: 'ma-proba', carteTitre: "Variable aléatoire discrète et loi" },
  { methodeId: 71, chapitreId: 'ma-va', carteTitre: "Loi faible des grands nombres" },
  { methodeId: 72, chapitreId: 'ma-proba', carteTitre: "Inégalité de Markov" },
  { methodeId: 73, chapitreId: 'ma-proba', carteTitre: "Loi faible des grands nombres" },
  { methodeId: 74, chapitreId: 'ma-proba', carteTitre: "Inégalité de Markov" },
  { methodeId: 75, chapitreId: 'ma-va', carteTitre: "Série génératrice" },
  { methodeId: 76, chapitreId: 'ma-va', carteTitre: "Lois usuelles (tableau)" },
  { methodeId: 77, chapitreId: 'ma-va', carteTitre: "Génératrice d'une somme" },
  { methodeId: 78, chapitreId: 'ma-ann', carteTitre: "Division euclidienne dans $\\mathbb{Z}$" },
  { methodeId: 79, chapitreId: 'ma-ann', carteTitre: "Racine et ordre de multiplicité" },
  { methodeId: 80, chapitreId: 'ma-ann', carteTitre: "Division euclidienne dans $\\mathbb{Z}$" },
  { methodeId: 81, chapitreId: 'ma-ann', carteTitre: "Division euclidienne dans $\\mathbb{Z}$" },
  { methodeId: 82, chapitreId: 'ma-ann', carteTitre: "Division euclidienne des polynômes" },
  { methodeId: 83, chapitreId: 'ma-ann', carteTitre: "Division euclidienne dans $\\mathbb{Z}$" },
  { methodeId: 84, chapitreId: 'ma-ann', carteTitre: "PGCD et théorème de Bézout" },
  { methodeId: 85, chapitreId: 'ma-ann', carteTitre: "PGCD et théorème de Bézout" },
  { methodeId: 86, chapitreId: 'ma-ann', carteTitre: "Corps" },
  { methodeId: 87, chapitreId: 'ma-gr', carteTitre: "Caractérisation d'un sous-groupe" },
  { methodeId: 88, chapitreId: 'ma-gr', carteTitre: "Sous-groupes de $(\\mathbb{Z},+)$" },
  { methodeId: 89, chapitreId: 'ma-gr', carteTitre: "Théorème de Lagrange" },
  { methodeId: 90, chapitreId: 'ma-gr', carteTitre: "Morphisme de groupes" },
  { methodeId: 91, chapitreId: 'ma-ann', carteTitre: "Racine et ordre de multiplicité" },
  { methodeId: 92, chapitreId: 'ma-3e-arith', carteTitre: "Décomposition en facteurs premiers" },
  { methodeId: 93, chapitreId: 'ma-3e-arith', carteTitre: "Décomposition en facteurs premiers" },
  { methodeId: 94, chapitreId: 'ma-3e-calclit1', carteTitre: "Trois identités remarquables" },
  { methodeId: 95, chapitreId: 'ma-3e-calclit1', carteTitre: "Trois identités remarquables" },
  { methodeId: 96, chapitreId: 'ma-3e-calclit1', carteTitre: "Trois identités remarquables" },
  { methodeId: 97, chapitreId: 'ma-3e-calclit1', carteTitre: "Trois identités remarquables" },
  { methodeId: 98, chapitreId: 'ma-3e-calclit1', carteTitre: "Trois identités remarquables" },
  { methodeId: 99, chapitreId: 'ma-3e-calclit2', carteTitre: "Équation $x^2 = a$" },
  { methodeId: 100, chapitreId: 'ma-3e-calclit2', carteTitre: "Équation $x^2 = a$" },
  { methodeId: 101, chapitreId: 'ma-3e-calclit2', carteTitre: "Inéquation" },
  { methodeId: 102, chapitreId: 'ma-3e-arith', carteTitre: "Décomposition en facteurs premiers" },
  { methodeId: 103, chapitreId: 'ma-3e-fonaffine', carteTitre: "Droite représentative de $f(x) = ax + b$" },
  { methodeId: 104, chapitreId: 'ma-3e-fonaffine', carteTitre: "Droite représentative de $f(x) = ax + b$" },
  { methodeId: 105, chapitreId: 'ma-3e-fonc', carteTitre: "Fonction, image, antécédent" },
  { methodeId: 106, chapitreId: 'ma-3e-fonc', carteTitre: "Fonction, image, antécédent" },
  { methodeId: 107, chapitreId: 'ma-3e-fonlin', carteTitre: "Représentation graphique d'une fonction linéaire" },
  { methodeId: 108, chapitreId: 'ma-3e-fonc', carteTitre: "Fonction, image, antécédent" },
  { methodeId: 109, chapitreId: 'ma-3e-fonlin', carteTitre: "Représentation graphique d'une fonction linéaire" },
  { methodeId: 110, chapitreId: 'ma-3e-fonlin', carteTitre: "Représentation graphique d'une fonction linéaire" },
  { methodeId: 111, chapitreId: 'ma-3e-proba', carteTitre: "Propriétés des probabilités" },
  { methodeId: 112, chapitreId: 'ma-3e-pytha', carteTitre: "Théorème de Pythagore" },
  { methodeId: 113, chapitreId: 'ma-3e-pytha', carteTitre: "Théorème de Pythagore" },
  { methodeId: 114, chapitreId: 'ma-3e-pytha', carteTitre: "Angles complémentaires dans un triangle rectangle" },
  { methodeId: 115, chapitreId: 'ma-3e-pytha', carteTitre: "Théorème de Pythagore" },
  { methodeId: 116, chapitreId: 'ma-3e-stats', carteTitre: "Moyenne" },
  { methodeId: 117, chapitreId: 'ma-3e-thales', carteTitre: "Théorème de Thalès" },
  { methodeId: 118, chapitreId: 'ma-3e-thales', carteTitre: "Théorème de Thalès" },
  { methodeId: 119, chapitreId: 'ma-3e-trisiml', carteTitre: "Côtés homologues proportionnels" }
];
